<table class="table table-hover table-condensed table-bordered table-striped table-filtrable table-paginable table-sortable" data-sort-cols="0" data-sort-dirs="asc">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Rôle</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    	<?php foreach ($utilisateurs as $utilisateur): ?>
    	<tr>
			<td><a href="<?= ROOT.'utilisateurs/modifier/'.$utilisateur['id_utilisateur'] ?>"><?= $this->escape($utilisateur['nom']) ?></a></td>
            <td><?= $this->escape($utilisateur['prenom']) ?></td>
			<td><?= ucfirst($this->escape($utilisateur['role'])) ?></td>
            <td class="col-actions">
                <div class="pull-right">
                    <a type="button" class="btn btn-primary btn-xs" href="<?= ROOT.'utilisateurs/modifier/'.$utilisateur['id_utilisateur'] ?>" title="Modifier l'utilisateur"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a type="button" class="btn btn-danger btn-xs btn-delete" href="<?= ROOT.'utilisateurs/supprimer/'.$utilisateur['id_utilisateur'] ?>" title="Supprimer l'utilisateur"  data-modal-content="Êtes-vous sur de vouloir supprimer cet utilisateur ?"><span class="glyphicon glyphicon-remove"></span></a>
                </div>
            </td>
		</tr>
		<?php endforeach; ?>
    </tbody>
</table>