<ul class="nav nav-tabs">
	<li class="active"><a href="#tab_informations" data-toggle="tab">Utilisateur</a></li>
</ul>

<div class="tab-content">

	<div class="tab-pane active" id="tab_informations">
		<?= $form = $this->form(Atomik::url('@ut_add'), null, array('class' => 'form-horizontal')) ?>
		<?= Form::generateFields($form, $fields) ?>

			<hr>

			<div class="form-group">
				<div class="col-lg-offset-2 col-lg-10">
					<?= $form->buttons('Ajouter l\'utilisateur', Atomik::url('@ut_all'), array('class' => 'btn btn-primary')) ?>
				</div>
			</div>
		</form>
	</div>

</div>

