<ul class="nav nav-tabs">
	<li class="active"><a href="#tab_informations" data-toggle="tab">Informations sur l'utilisateur</a></li>
</ul>

<div class="tab-content">

	<div class="tab-pane active" id="tab_informations">
		<?= $form = $this->form(ROOT.'utilisateurs/modifier/'.$utilisateur['id_utilisateur'], null, array('class' => 'form-horizontal')) ?>
		<?= Form::generateFields($form, $fields, $utilisateur) ?>

			<hr>
			
			<div class="form-group">
				<div class="col-lg-offset-2 col-lg-10">
					<?= $form->buttons('Modifier l\'utilisateur', ROOT.'utilisateurs', array('class' => 'btn btn-primary')) ?>
				</div>
			</div>
		</form>
	</div>

</div>