<ul class="nav nav-tabs">
	<li class="active"><a href="#tab_informations" data-toggle="tab">Informations sur le client</a></li>
</ul>

<div class="tab-content">

	<div class="tab-pane active" id="tab_informations">
		<?= $form = $this->form(Atomik::url('@cl_upd', array('id' => $client['id_client'])), null, array('class' => 'form-horizontal', 'enctype' => 'multipart/form-data')) ?>
		<?= Form::generateFields($form, $fields, $client) ?>

			<hr>

			<div class="form-group">
				<div class="col-lg-offset-2 col-lg-4">
					<?= $form->buttons('Modifier le client', Atomik::url('@cl_all'), array('class' => 'btn btn-primary')) ?>
				</div>
			</div>
		</form>
	</div>

</div>