<!doctype html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<title>Atomik</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<link href="<?php echo $this->asset('assets/css/bootstrap.min.css') ?>" rel="stylesheet">
		<link href="<?php echo $this->asset('assets/css/app.css') ?>" rel="stylesheet">

		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="<?php echo $this->asset('assets/js/html5shiv.js') ?>"></script>
		<![endif]-->

		<?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBarHead(); ?>
	</head>
	<body>

		<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
			<div class="container">

				<div class="navbar-header">
					<a class="navbar-brand" href="<?= ROOT ?>"><span class="glyphicon glyphicon-record"></span> Atomik</a>
				</div>

			</div>
		</header>

		<section>
			<div class="container">

				<div class="col-lg-offset-3 col-lg-9">
					<div class="page-header">
						<h1>Connexion</h1>
					</div>

					<?php if (count($this['flash_messages'])): ?>
						<?php foreach ($this['flash_messages'] as $label => $messages): ?>
							<?php foreach ($messages as $message): ?>
								<div class="alert alert-dismissable alert-<?php echo $label ?>">
									<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
									<?php echo $message ?>
								</div>
							<?php endforeach; ?>
						<?php endforeach; ?>
					<?php endif ?>
				
					<div id="content" role="main">
						<?= $form = $this->form(ROOT.'connexion', null, array('class' => 'form-horizontal')) ?>
							<div class="form-group">
								<label for="identifiant" class="col-lg-2">Identifiant</label>
								<div class="col-lg-4">
									<input type="text" class="form-control" id="identifiant" name="identifiant" placeholder="Identifiant" value="<?= $data['identifiant'] ?>">
								</div>
							</div>
							<div class="form-group">
								<label for="mot_de_passe" class="col-lg-2">Mot de passe</label>
								<div class="col-lg-4">
									<input type="password" class="form-control" id="mot_de_passe" name="mot_de_passe" placeholder="Mot de passe">
								</div>
							</div>
							<div class="form-group">
								<div class="col-lg-offset-2 col-lg-4">
									<button type="submit" class="btn btn-primary">Se connecter</button>
								</div>
							</div>
						</form>
					</div>
				</div>

			</div>
		</section>
		<footer>
			<div class="container">
				<p>&copy; <?php echo date('Y') ?>, Atomik - <small>Conception & Réalisation : <a href="http://zes.sx" class="external">@zessx</a></small></p>
			</div>
		</footer>

		<?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBar(); ?>

		<script src="<?php echo $this->asset('assets/js/jquery-1.9.1.min.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/bootstrap.min.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/app.js') ?>"></script>
	</body>
</html>
