<!doctype html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<title><?= $title ?> - Loccapi</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<link href="<?php echo $this->asset('assets/css/bootstrap.min.css') ?>" rel="stylesheet">
		<link href="<?php echo $this->asset('assets/css/plugins/bootstrap-datetimepicker.min.css') ?>" rel="stylesheet">
		<link href="<?php echo $this->asset('assets/css/app.css') ?>" rel="stylesheet">

		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="<?php echo $this->asset('assets/js/html5shiv.js') ?>"></script>
		<![endif]-->

		<?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBarHead(); ?>
	</head>
	<body>

		<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
			<div class="container">

				<div class="navbar-header">
					<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
						<span class="sr-only">Menu</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>	
					<a class="navbar-brand" href="<?= ROOT ?>"><span class="glyphicon glyphicon-record"></span> Loccapi</a>
				</div>

				<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
					
					<ul class="nav navbar-nav pull-right hidden-xs">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<span class="glyphicon glyphicon-user"></span>
								<span class="username"> Bienvenue, <?= Atomik::get('session.user.name') ?></span> <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="<?= ROOT ?>utilisateurs/mon-compte"><span class="glyphicon glyphicon-pencil"></span> Mon compte</a></li>
								<li><a href="<?= ROOT ?>deconnexion"><span class="glyphicon glyphicon-off"></span> Déconnexion</a></li>
							</ul>
						</li>
					</ul>

					<ul class="nav navbar-nav">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Clients <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="<?= ROOT ?>clients">Clients</a></li>
								<li><a href="<?= ROOT ?>etablissements">Établissements</a></li>
								<li><a href="<?= ROOT ?>emplacements">Emplacements</a></li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Machines <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="<?= ROOT ?>machines">Machines</a></li>
								<li><a href="<?= ROOT ?>machines/types">Types de machines</a></li>
								<li><a href="<?= ROOT ?>fabricants">Fabricants</a></li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Interventions <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="<?= ROOT ?>interventions">Interventions</a></li>
								<li><a href="<?= ROOT ?>articles">Articles</a></li>
								<li><a href="<?= ROOT ?>alertes">Alertes</a></li>
							</ul>
						</li>
						<?php if(ROLE_ADMIN) { ?>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Administration <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="<?= ROOT ?>utilisateurs">Utilisateurs</a></li>
							</ul>
						</li>
						<?php } ?>
						<li class="visible-xs"><a href="<?= ROOT ?>utilisateurs/mon-compte">Mon compte</a></li>
						<li class="visible-xs"><a href="<?= ROOT ?>deconnexion">Déconnexion</a></li>
					</ul>
					
				</nav>
			</div>
		</header>

		<section>
			<div class="container">

				<div class="col-md-3 visible-lg">
					<div class="sidenav" role="complementary" data-spy="affix">
						<ul class="nav bs-sidenav">
							<li><h4><span class="glyphicon glyphicon-earphone"></span> Clients</h4></li>
							<li><a <?= Atomik::uriMatch('/clients*/') ? 'class="active"' : '' ?> href="<?= ROOT ?>clients">Clients</a></li>
							<li><a <?= Atomik::uriMatch('/etablissements*/') ? 'class="active"' : '' ?> href="<?= ROOT ?>etablissements">Établissements</a></li>
							<li><a <?= Atomik::uriMatch('/emplacements*/') ? 'class="active"' : '' ?> href="<?= ROOT ?>emplacements">Emplacements</a></li>

							<li><h4><span class="glyphicon glyphicon-cog"></span> Machines</h4></li>
							<li><a <?= Atomik::uriMatch('/machines(?!\/types)*/') ? 'class="active"' : '' ?> href="<?= ROOT ?>machines">Machines</a></li>
							<li><a <?= Atomik::uriMatch('/machines\/types*/') ? 'class="active"' : '' ?> href="<?= ROOT ?>machines/types">Types de machines</a></li>
							<li><a <?= Atomik::uriMatch('/fabricants*/') ? 'class="active"' : '' ?> href="<?= ROOT ?>fabricants">Fabricants</a></li>

							<li><h4><span class="glyphicon glyphicon-wrench"></span> Interventions</h4></li>
							<li><a <?= Atomik::uriMatch('/interventions*/') ? 'class="active"' : '' ?> href="<?= ROOT ?>interventions">Interventions</a></li>
							<li><a <?= Atomik::uriMatch('/articles*/') ? 'class="active"' : '' ?> href="<?= ROOT ?>articles">Articles</a></li>
							<li><a class="<?= Atomik::uriMatch('/alertes*/') ? 'active' : '' ?><?= NB_ALERTES > 0 ? ' text-danger ' : '' ?>" href="<?= ROOT ?>articles">Alertes<?= NB_ALERTES > 0 ? '  <span class="label label-danger">'.NB_ALERTES.'</span>' : '' ?></a></li>

							<?php if(ROLE_ADMIN) { ?>
							<li><h4><span class="glyphicon glyphicon-stats"></span> Administration</h4></li>
							<li><a <?= Atomik::uriMatch('/utilisateurs(?!/mon-compte)*/') ? 'class="active"' : '' ?> href="<?= ROOT ?>utilisateurs">Utilisateurs</a></li>
							<?php } ?>

							<li><h4><span class="glyphicon glyphicon-user"></span> Mon compte</h4></li>
							<li><a <?= Atomik::uriMatch('/utilisateurs/mon-compte*/') ? 'class="active"' : '' ?> href="<?= ROOT ?>utilisateurs/mon-compte">Mon compte</a></li>
							<li><a href="<?= ROOT ?>deconnexion">Déconnexion</a></li>
						</ul>
					  </div>
				</div>

				<div class="col-md-12 col-lg-9">
					<div class="page-header">
						<h1><?php echo $title ?> <small><?php echo $subtitle ?></small></h1>
					</div>
					<?php if (count($this['flash_messages'])): ?>
						<?php foreach ($this['flash_messages'] as $label => $messages): ?>
							<?php foreach ($messages as $message): ?>
								<div class="alert alert-dismissable alert-<?php echo $label ?>">
									<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
									<?php echo $message ?>
								</div>
							<?php endforeach; ?>
						<?php endforeach; ?>
					<?php endif ?>
				
					<div id="content" role="main">
						<?php echo $contentForLayout; ?>
					</div>
				</div>

			</div>
		</section>
		<footer>
			<div class="container">
				<p>&copy; <?php echo date('Y') ?>, Loccapi - <small>Conception & Réalisation : <a href="http://www.alancia.fr" class="external">Alancia</a></small></p>
			</div>
		</footer>

		<?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBar(); ?>

		<script src="<?php echo $this->asset('assets/js/jquery-1.9.1.min.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/bootstrap.min.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/plugins/jquery.datatables.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/plugins/bootstrap-datetimepicker.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/plugins/bootstrap.typeahead.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/plugins/DT_bootstrap.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/app.js') ?>"></script>
	</body>
</html>
