<!doctype html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<title><?= $title ?> - Atomik</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->asset('assets/images/favicon.ico') ?>" />

		<link href="<?php echo $this->asset('assets/css/bootstrap.min.css') ?>" rel="stylesheet">
		<link href="<?php echo $this->asset('assets/css/plugins/jquery.fancybox.css') ?>" rel="stylesheet">
		<link href="<?php echo $this->asset('assets/css/app.min.css') ?>" rel="stylesheet">

		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="<?php echo $this->asset('assets/js/html5shiv.js') ?>"></script>
		<![endif]-->

		<?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBarHead(); ?>
	</head>
	<body>

		<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
			<div class="container">

				<div class="navbar-header">
					<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
						<span class="sr-only">Menu</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="<?= Atomik::url('@home') ?>"><span class="glyphicon glyphicon-record"></span> Atomik</a>
				</div>

				<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">

					<ul class="nav navbar-nav pull-right hidden-xs">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<span class="glyphicon glyphicon-user"></span>
								<span class="username"> Bienvenue, <?= Atomik::get('session.user.name') ?></span> <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="<?= Atomik::url('@ut_account') ?>"><span class="glyphicon glyphicon-user"></span> Mes informations</a></li>
								<li><a href="<?= Atomik::url('@ut_upd_pwd') ?>"><span class="glyphicon glyphicon-wrench"></span> Modifier mon mot de passe</a></li>
								<li><a href="<?= Atomik::url('@logout') ?>"><span class="glyphicon glyphicon-off"></span> Déconnexion</a></li>
							</ul>
						</li>
					</ul>

					<ul class="nav navbar-nav">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Clients <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="<?= Atomik::url('@cl_all') ?>">Clients</a></li>
							</ul>
						</li>
						<li class="visible-xs"><a href="<?= Atomik::url('@ut_account') ?>">Mes informations</a></li>
						<li class="visible-xs"><a href="<?= Atomik::url('@ut_upd_pwd') ?>">Modifier mon mot de passe</a></li>
						<li class="visible-xs"><a href="<?= Atomik::url('@logout') ?>">Déconnexion</a></li>
					</ul>

				</nav>
			</div>
		</header>

		<section>
			<div class="container">

				<div class="col-md-3 visible-lg">
					<div class="sidenav" role="complementary" data-spy="affix">
						<ul class="nav bs-sidenav">

							<li><h4><span class="glyphicon glyphicon-earphone"></span> Gestion des clients</h4></li>
							<li><a <?= Atomik::uriMatch('/clients*/') ? 'class="active"' : '' ?> href="<?= Atomik::url('@cl_all') ?>">Clients</a></li>

							<?php if(ROLE_ADMIN) { ?>
							<li><h4><span class="glyphicon glyphicon-stats"></span> Administration</h4></li>
							<li><a <?= Atomik::uriMatch('/utilisateurs(?!\/mon-compte)*/') ? 'class="active"' : '' ?> href="<?= Atomik::url('@ut_all') ?>">Utilisateurs</a></li>
							<?php } ?>

							<li><h4><span class="glyphicon glyphicon-user"></span> Gestion de l'extranet</h4></li>
							<li><a <?= Atomik::uriMatch('utilisateurs\/mon-compte(?!\/mot-de-passe)*') ? 'class="active"' : '' ?> href="<?= Atomik::url('@ut_account') ?>">Mes informations</a></li>
							<li><a <?= Atomik::uriMatch('utilisateurs\/mon-compte\/mot-de-passe*') ? 'class="active"' : '' ?> href="<?= Atomik::url('@ut_upd_pwd') ?>">Modifier mon mot de passe</a></li>
							<li><a href="<?= Atomik::url('@logout') ?>">Déconnexion</a></li>
						</ul>
					  </div>
				</div>

				<div class="col-md-12 col-lg-9">
					<div class="page-header">
						<h1><?php echo $title ?> <small><?php echo $subtitle ?></small></h1>
					</div>

					<?php if (count($this['flash_messages'])): ?>
						<?php foreach ($this['flash_messages'] as $label => $messages): ?>
							<?php foreach ($messages as $message): ?>
								<div class="alert alert-dismissable alert-<?php echo $label ?>">
									<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
									<?php echo $message ?>
								</div>
							<?php endforeach; ?>
						<?php endforeach; ?>
					<?php endif ?>

					<div id="content" role="main">
						<?php echo $contentForLayout; ?>
					</div>
				</div>

			</div>
		</section>
		<footer>
			<div class="container">
				<p>&copy; <?php echo date('Y') ?>, Atomik - <small>Conception & Réalisation : <a href="http://zes.sx" class="external">@zessx</a></small></p>
			</div>
		</footer>

		<?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBar(); ?>

		<script src="<?php echo $this->asset('assets/js/jquery-1.9.1.min.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/bootstrap.min.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/plugins/jquery.datatables.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/plugins/bootstrap.datetimepicker.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/plugins/bootstrap.typeahead.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/plugins/DT_bootstrap.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/plugins/jquery.fancybox.js') ?>"></script>
		<script src="<?php echo $this->asset('assets/js/app.min.js') ?>"></script>
	</body>
</html>
